// Lista de marcas de coches disponibles en España
export const carBrands = [
  "Abarth",
  "Alfa Romeo",
  "Alpine",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "BYD",
  "Citroën",
  "Cupra",
  "Dacia",
  "DS",
  "Ferrari",
  "Fiat",
  "Ford",
  "Honda",
  "Hyundai",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Maserati",
  "Mazda",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Opel",
  "Peugeot",
  "Porsche",
  "Renault",
  "SEAT",
  "Skoda",
  "Smart",
  "SsangYong",
  "Subaru",
  "Suzuki",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
]

// Modelos por marca (versión simplificada)
const carModelsByBrand: Record<string, string[]> = {
  Audi: ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "R8"],
  BMW: [
    "Serie 1",
    "Serie 2",
    "Serie 3",
    "Serie 4",
    "Serie 5",
    "Serie 6",
    "Serie 7",
    "Serie 8",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "i8",
    "iX",
  ],
  Citroën: ["C1", "C3", "C4", "C5", "Berlingo", "C3 Aircross", "C4 Cactus", "C5 Aircross", "SpaceTourer"],
  Dacia: ["Sandero", "Logan", "Duster", "Spring", "Jogger"],
  Fiat: ["500", "Panda", "Tipo", "500X", "500L"],
  Ford: ["Fiesta", "Focus", "Mondeo", "Kuga", "Puma", "EcoSport", "Mustang", "Explorer", "Transit"],
  Honda: ["Jazz", "Civic", "HR-V", "CR-V", "e"],
  Hyundai: ["i10", "i20", "i30", "Kona", "Tucson", "Santa Fe", "IONIQ", "NEXO"],
  Kia: ["Picanto", "Rio", "Ceed", "XCeed", "Stonic", "Niro", "Sportage", "Sorento", "EV6"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-30", "CX-5", "MX-5", "MX-30"],
  "Mercedes-Benz": [
    "Clase A",
    "Clase B",
    "Clase C",
    "Clase E",
    "Clase S",
    "CLA",
    "CLS",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
  ],
  Nissan: ["Micra", "Juke", "Qashqai", "X-Trail", "Leaf", "Ariya"],
  Opel: ["Corsa", "Astra", "Crossland", "Grandland", "Mokka", "Combo", "Zafira"],
  Peugeot: ["108", "208", "308", "508", "2008", "3008", "5008", "Rifter", "Traveller"],
  Renault: ["Clio", "Captur", "Mégane", "Arkana", "Kadjar", "Scénic", "Espace", "Talisman", "Twingo", "ZOE"],
  SEAT: ["Ibiza", "León", "Arona", "Ateca", "Tarraco", "Alhambra", "Mii"],
  Skoda: ["Fabia", "Scala", "Octavia", "Superb", "Kamiq", "Karoq", "Kodiaq", "Enyaq"],
  Toyota: ["Aygo", "Yaris", "Corolla", "Camry", "C-HR", "RAV4", "Highlander", "Land Cruiser", "Prius", "Mirai", "bZ4X"],
  Volkswagen: ["Polo", "Golf", "Passat", "Arteon", "T-Cross", "T-Roc", "Tiguan", "Touareg", "ID.3", "ID.4", "ID.5"],
  Volvo: ["XC40", "XC60", "XC90", "S60", "S90", "V60", "V90", "C40"],
}

// Función para obtener los modelos de una marca
export function getCarModels(brand: string): string[] {
  return carModelsByBrand[brand] || []
}

